[project]
name = "app"
version = "0.1.0"
description = "Kafka Streams & Processing practice with Faust"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faust-streaming>=0.11.3",
]
